### ISSUE TITLE
wink-js doesn't handle wink api being down and causes crashes.

### ISSUE THREAD

**Issue by msroest** [winfinit/wink-js#3]
TypeError: Cannot read property 'data' of undefined
at /usr/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:223:41
at IncomingMessage. (/usr/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:74:7)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:905:12)
at nextTickCallbackWith2Args (node.js:478:9)
at process._tickCallback (node.js:392:17)

**Comment by msroest** [comment]
Since the PR is merged can we get a new release of the module?

Thanks!

**Comment by winfinit** [comment]
absolutely :) thank you for this fix, 0.1.0 was published.

**Comment by ramarnat** [comment]
I am still seeing this issue with the latest version

```
 SyntaxError: Unexpected end of input
     at Object.parse (native)
     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:66:19)
     at emitNone (events.js:72:20)
     at IncomingMessage.emit (events.js:166:7)
     at endReadableNT (_stream_readable.js:905:12)
     at doNTCallback2 (node.js:441:9)
     at process._tickCallback (node.js:355:17)
 raw message
 /usr/local/lib/node_modules/homebridge-wink/index.js:118
          for (var i = 0; i < devices.data.length; i++) {
                                     ^

 TypeError: Cannot read property 'data' of undefined
     at /usr/local/lib/node_modules/homebridge-wink/index.js:118:33
     at /usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:237:9
     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:73:7)
     at emitNone (events.js:72:20)
     at IncomingMessage.emit (events.js:166:7)
     at endReadableNT (_stream_readable.js:905:12)
     at doNTCallback2 (node.js:441:9)
     at process._tickCallback (node.js:355:17)
```

**Comment by ramarnat** [comment]
The previous issue turned out to be because I had an extra `username` kvp in the config.json, but maybe that could be handled as well. Now I am getting the following message:

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:66:19)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
raw message <!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Offline for Maintenance</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/maintenance.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:120
         accessToken = response.access_token;
                               ^
homebridge |
TypeError: Cannot read property 'access_token' of undefined
    at /usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:120:28
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-wink/node_modules/wink-js/index.js:73:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by winfinit** [comment]
@ramarnat based on raw message content, it looks like API is offline for maintenance.

**Comment by ramarnat** [comment]
Ha. I got that part. I am wondering if there was some error handling that can be put in so it doesnt die.

**Comment by winfinit** [comment]
i didn't look at this in a while now... i've added few checks to handle this specific condition

**Comment by winfinit** [comment]
is this still an issue?

**Comment by ramarnat** [comment]
Its been pretty stable so far. So thank you.
